---
apiVersion: v1
kind: Service
metadata:
  name: project-lb
  namespace: project
spec:
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
